### ISSUE TITLE
Provide option to get blob instead of Base64 URL

### ISSUE THREAD

**Issue by nick11roberts** [Foliotek/Croppie#185] opened 2016-08-09 20:44 UTC
In iOS Safari when I choose a file, crop it, and submit using Croppie, a message appears saying "A problem occurred with this webpage so it was reloaded" and a prompt saying "Are you sure you want to submit this form again?" appears, often resulting in the same message appearing, and sometimes it just submits the form and works. In all other browsers I've tried, Android, Chrome, etc., it has worked just fine. 

My javascript is based off of the examples on http://foliotek.github.io/Croppie/

Javascript code (`imageupload.js`): 
```js
$( document ).ready(function() {
   var $uploadCrop;

   function readFile(input) {
      if (input.files && input.files[0]) {
         var reader = new FileReader();
         reader.onload = function (e) {
            $uploadCrop.croppie('bind', {
               url: e.target.result
            });
            $('.upload-demo').addClass('ready');
         }
         reader.readAsDataURL(input.files[0]);
      }
   }

   $uploadCrop = $('#upload-demo').croppie({
      viewport: {
         width: 530,
         height: 300,
         type: 'square'
      },
      boundary: {
         width: 600,
         height: 370
      }
   });

   $('#upload').on('change', function () { readFile(this); });
   $('.upload-result').on('click', function (ev) {
      $uploadCrop.croppie('result', {
         type: 'canvas',
         size: 'original'
      }).then(function (resp) {
         $('#image-data').val(resp);
         $('#form').submit();
      });
   });

});
```

html code (`upload.html`): 
```html
<html>
   <head>
      <title>upload</title>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script src="node_modules/croppie/croppie.js"></script>
      <script src="imageupload.js"></script>
      <link rel="stylesheet" href="node_modules/croppie/croppie.css" />
   </head>
   <body>

      <form enctype="multipart/form-data" action="/handleupload/" id="form" method="post">
         <input type="file" id="upload" value="Choose a file">
         <div id="upload-demo"></div>
         <input type="hidden" id="image-data" name="image-data">
         <a href="#" class="upload-result">Send</a>
      </form>

   </body>
</html>
```
Am I doing this correctly?

**Comment by thedustinsmith** [comment] 2016-08-09 20:58
You might get a more useful error if you use Safari's web inspector to debug iOS.  With a quick glance at your code I don't see anything that should cause an issue, but the error that you're getting isn't very helpful.

**Comment by sonnybaker** [comment] 2016-08-10 10:49
Hey @nick11roberts - the issue is that the POST size is too large for iOS Safari and the browser memory becomes exhausted. It's actually a webkit bug: https://bugs.webkit.org/show_bug.cgi?id=84168

Our solution was to send the image data to the server via AJAX, and then after a successful response submit the rest of the form normally, minus the Base64 strings. It's a frustrating workaround, but we haven't had any problems since switching to that method.

**Comment by thedustinsmith** [comment] 2016-08-10 12:39
Interesting.

There's some info in this case (#160) about converting base64 data to blobs, I wonder if the form submit would work if you submitted through a `<input type="file" />` and `Blob` instead.

I might play around with it and see what I can find.  If that resolves the issues, maybe providing a blob instead of a base64 image would be better.

**Comment by Zapnologica** [comment] 2016-09-21 11:52
Agreed. Blob output should definitely be an option. Base64 string is silly in my opinion.

**Comment by thedustinsmith** [comment] 2016-09-21 13:30
@Zapnologica  It's in master.  You can be a guinea pig - since you seem pretty against base64.

**Comment by williamoconnor** [comment] 2016-10-15 02:26
It is not updated in the minified file, just so all are aware

**Comment by thedustinsmith** [comment] 2016-10-21 15:54
Will be in `2.4.0`

**Closed by thedustinsmith** 2016-10-21 15:54 UTC
Labels: New Feature

**Comment by Rahu-ju** [comment] 2018-12-26 18:12
@nick11roberts,I need to save the viewport size image. So i use `size:'viewport'` . But instead viewport size image its save the original image size. Here is my code..

```$('#upload').on('change', function () { readFile(this); });
   $('.upload-result').on('click', function (ev) {
      $uploadCrop.croppie('result', {
         type: 'canvas',
         **size: 'viewport'**
      }).then(function (resp) {
         $('#image-data').val(resp);
         $('#form').submit();
      });
   });
```
Thanks in advance.
