### ISSUE TITLE
Problems since update to v2.1.0

### ISSUE THREAD

**Issue by J0nKn1ght** [Foliotek/Croppie#123] opened 2016-04-13 13:38 UTC
Hi,

Since updating to v2.1.0, I have a few issues that I can't seem to work around, and I was wondering if you could check whether I'm doing something odd in my code.

I've created a jsFiddle to try and reproduce the issues that I'm having: [http://jsfiddle.net/JonKnight/g6y0njrc/](http://jsfiddle.net/JonKnight/g6y0njrc/)

When you first run it, and click on the 'Show Dialog' button, the js rebinds the image, and tries to set the zoom factor to 1.0.  However, this seems to leave the image at the top left of the container, rather than centering it.  As soon as you change the slider, the image is repositioned correctly.

Is there something I can do to get it to center correctly?

On the jsFiddle, I tried to set the enableOrientation option, but when I do, the image isn't displayed.  I'm wasn't sure whether this was due to CORS issues on the canvas, so I tried referencing a file in an Azure blob store, and have set the AllowedOrigins on the blob storage container to '*', but it still doesn't get displayed.  This isn't an issue with my normal use of croppie, but I wondered if you knew what the problem was.

Finally, this is actually another feature request for the rotation, but is it possible to set the origin of the rotation to the center-point of the container?  Currently, if you center and zoom the image so that it fits the viewport, and then rotate, the portion of the image that you centered can end up completely outside the viewport.

Thanks.

**Comment by thedustinsmith** [comment] 2016-04-13 13:57
Just wanted to say thanks for submitting a jsfiddle.  It's so much easier to debug these issues with examples.  I'm looking at the issues right now.

**Comment by J0nKn1ght** [comment] 2016-04-13 14:12
That's no problem.  Whenever something doesn't work, my first line of investigation is always 'I must have done something wrong', so I find creating a jsFiddle to try and remove as many of the other factors involved is always a useful first step!

**Comment by thedustinsmith** [comment] 2016-04-13 14:14
Haha - the world could use more developers like you!

The problem was the first time you called `bind()` the croppie wasn't visible, so you were correctly calling bind again when your modal was shown.

However, croppie didn't refresh the center point when you called bind the second time without any parameters.  So when you called setZoom it was zooming to the top left of the image which shifted it that direction.  Good catch on this!

I'm looking at the enable orientation bug now.

**Comment by J0nKn1ght** [comment] 2016-04-13 14:17
Wow! That is impressively fast fixing - thanks!

**Comment by thedustinsmith** [comment] 2016-04-13 14:38
Ok, both the issues you found are now resolved in master.  Thanks for catching those.

As far as the feature request, that one gets a little more tricky.  However, I agree with the need for it.

I have a rough idea of how it could be implemented:  I think after we redraw the canvas with the new orientation, we need to update the transform-origin.

So if we had a 200x100 image, and we were zoomed in on the center point of 150,50 (`transform-origin: 150px 50px`).  Then we rotate that image 90 degrees, our new image dimensions are 100x200.  Our new would then be `transform-origin: 50px 150px` (inverting the x and y).  That's how it would work in my mind.  I'm sure there are some flaws to it, but that would be a good start.

I don't have the time to get to it right now.  I know we have some development coming up in the future that would require this functionality to be ironed out a bit, but I'm not sure when that's scheduled.

If you want to submit a PR, we'd be more than happy to merge it in.

**Comment by erperejildo** [comment] 2016-05-23 14:52
I had a similar problem with initial image position and maybe it is related with that one.
When image loads has this style:
`-webkit-transform: translate3d(-28.50000046477921px, -454.33333444880344px, 0px) scale(0.7389162561576355);`
And should be around -100 instead -454. I can't see any image until I change the slider.
Besides I already downloaded the plugin through bower and the croppie.js is different.
Is that ok?
The problem is on desktop and mobile as well.

**Comment by thedustinsmith** [comment] 2016-06-23 17:22
@erperejildo are you still having problems?  If so - could you open up a separate case and put a more detailed explanation.  I may be able to help then.  

I'm going to close this case and open another one for the rotation around the center of the image.

**Closed by thedustinsmith** 2016-06-23 17:22 UTC

**Comment by erperejildo** [comment] 2016-07-29 11:49
Apologies for the delay. Was fixed
