### ISSUE TITLE
Result using original option doesn't return cropped region

### ISSUE THREAD

**Issue by yusuf-khamis** [Foliotek/Croppie#409] opened 2017-10-31 13:20 UTC
so exactly if you set option size to original instead of viewport it returns the image but cropped from 0,0, sizeY,sizeX of the image dimensions instead of the actual cropped part, is this how its supposed to work because my understanding is it should return cropped image but with the size relative to the image size not the viewport size

**Comment by liran-co** [comment] 2017-11-02 13:48
I'm having the same issue

**Comment by diachedelic** [comment] 2017-11-29 07:54
I have this issue when calling `croppie.result()` before the user does any zooming.

**Comment by diachedelic** [comment] 2017-11-29 11:13
I think I have found the issue, its a result of prematurely calling `self.elements.preview.getBoundingClientRect()`, which returns incorrect values.
```
    function _updatePropertiesFromImage() {
        var self = this,
            ...
            img = self.elements.preview,
            imgData = self.elements.preview.getBoundingClientRect(),
            ...

        ...

        self._originalImageWidth = imgData.width;
        self._originalImageHeight = imgData.height;
       ...
   }
...
```
`imgData.width === 344` but `img.width === 480` (as it should be).  Is there any reason `img.width` is not used directly here?

**Comment by diachedelic** [comment] 2017-11-29 12:22
Oh this appears to be caused by #398 which isn't released yet - how frustrating!  Can we have a 2.5.2 please?

**Comment by thedustinsmith** [comment] 2017-12-08 14:15
Yeah - I plan on releasing 2.5.2 soon, sorry.

**Comment by thedustinsmith** [comment] 2017-12-08 14:15
Going to go ahead and close this one since it's fixed in the next release.

**Closed by thedustinsmith** 2017-12-08 14:15 UTC
