### ISSUE TITLE
enforceBoundary cropping wrong position

### ISSUE THREAD

**Issue by bellsenawat** [Foliotek/Croppie#258] opened 2016-12-07 07:10 UTC
From this issue [https://github.com/Foliotek/Croppie/issues/163](url)

At one thing I got this problems on Safari when using enforceBoundary 

then I update js file and change to using rawcanvas

I test many times the result of image position is not the same crop modal. 

![screen shot 2016-12-07 at 2 01 26 pm](https://cloud.githubusercontent.com/assets/5281760/20958032/e944424c-bc85-11e6-842a-49345c01dc6b.png)

as an attached this is what I see when I cropping, after that the return result just show me only blank image but...... if I move image to left of boundary

![screen shot 2016-12-07 at 2 05 53 pm](https://cloud.githubusercontent.com/assets/5281760/20958093/606b0752-bc86-11e6-9648-c9c20614066d.png)
 

this is result 

![2](https://cloud.githubusercontent.com/assets/5281760/20958109/79d1654c-bc86-11e6-85aa-2785e10b0344.png)

**Comment by bellsenawat** [comment] 2016-12-13 04:41
Look like same problems
https://github.com/Foliotek/Croppie/issues/247

**Comment by thedustinsmith** [comment] 2017-02-02 18:47
Agreed - duplicate of #247

**Closed by thedustinsmith** 2017-02-02 18:47 UTC
