### ISSUE TITLE
Site navigation not working

### ISSUE THREAD

**Issue by MarioJuniorPro** [Foliotek/Croppie#464] opened 2018-01-30 18:07 UTC
## Expected Behavior
Access link

## Steps to Reproduce the Problem

  1. Access https://foliotek.github.io/Croppie/
  2. Try to navigate in Documentation or Demos links
  1.
  
## Specifications

  - Browser: Chrome
  - Version:

**Comment by thedustinsmith** [comment] 2018-01-30 18:50
Weird.  Thanks for the heads up.  

Maybe it's caused by us not closing a tag somewhere?  Just doing `$('body').scrollTop(100)` doesn't do anything either.

**Comment by thedustinsmith** [comment] 2018-02-05 14:33
This is fixed.  Thanks again.

**Closed by thedustinsmith** 2018-02-05 14:33 UTC
