### ISSUE TITLE
White or No image on mobile chrome upload

### ISSUE THREAD

**Issue by geraldarcega** [Foliotek/Croppie#121] opened 2016-04-12 10:02 UTC
Hi! I'm trying to upload an image to the demo site using Chrome in my Android phone but I'm getting white or no image after uploading the image

**Comment by thedustinsmith** [comment] 2016-04-12 14:07
Duplicate of #117.

I commited the code into master, but then got sidetracked as I was merging it to the gh-pages branch. 

Sorry about that.  It's fixed on the demo site now.

**Closed by thedustinsmith** 2016-04-12 14:07 UTC

**Comment by geraldarcega** [comment] 2016-04-12 14:12
Great! thanks!
