### ISSUE TITLE
Image not centering if cropping to a smaller result

### ISSUE THREAD

**Issue by tnrnz** [Foliotek/Croppie#238] opened 2016-11-04 10:22 UTC
It seems that the plugin is having a hard time centering when cropping the image to smaller view.
![croppie1](https://cloud.githubusercontent.com/assets/8624933/20002355/64777428-a2bb-11e6-8603-d48d02d1abc1.PNG)
![croppie2](https://cloud.githubusercontent.com/assets/8624933/20002357/65cb888c-a2bb-11e6-8422-6171e88cc4ba.PNG)

This is the code:
`$uploadCrop.croppie('result', {
				type: 'base64',
				format: 'png',
				size: {width: 1000, height: 1000}
			}).then(function (resp) {
				$('#img-output').attr('src', resp);
			});`

This was fixed if I removed the 'size' parameter. I need the parameter though.

**Comment by thedustinsmith** [comment] 2016-11-04 13:20
Interesting.  Could you put together demo demonstrating the whole issue?  I don't know what you mean by "cropping the image to smaller view".

Just a heads up, I've seen croppie do something like this when the croppie element is in a modal and it's not completely shown before the `bind()` is complete.

**Comment by tnrnz** [comment] 2016-11-05 03:29
Here's a demo of it:
http://codepen.io/tnrnz/pen/KNKLbN?editors=1100

and yes, I implemented this on a modal, I used the bind() after the modal was completely shown.

**Comment by thedustinsmith** [comment] 2016-11-05 15:06
Thanks for putting together the demo - I definitely see the issue now.  I'm guessing that broke when I fixed it for safari/IE.  I won't have time to work on this for a couple of weeks - so if you want to dig into it, the issue is somewhere in this function: https://github.com/Foliotek/Croppie/blob/master/croppie.js#L949

**Comment by thedustinsmith** [comment] 2017-02-02 18:58
I'm going to close this one in favor of #247 - but you get credit for finding it first.  That case just has more traction right now.

**Closed by thedustinsmith** 2017-02-02 18:58 UTC

**Comment by joelmatisa** [comment] 2019-08-12 23:32
hi there,
who could solve this because I have the same bug
